// <auto-generated />
namespace Bus_Station.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addisActivecolumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addisActivecolumn));
        
        string IMigrationMetadata.Id
        {
            get { return "202012190923105_add isActive column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
